// Generated by CoffeeScript 1.7.1
(function() {
  var conn, fs, http, net, server, spdy, url;

  fs = require('fs');

  spdy = require('spdy');

  http = require('http');

  net = require('net');

  url = require('url');

  conn = null;

  server = net.createServer(function(socket) {
    console.log('socket');
    conn = new spdy.Connection(socket, {
      isServer: true,
      client: false
    }, server);
    conn._setVersion(3.0);
    conn.on('error', function(err) {
      return console.error(err);
    });
    return conn.on('stream', function(stream) {
      console.log('stream');
      stream.on('data', function(data) {
        console.log(data.toString('binary'));
        stream.write('hello world!\n');
        return stream.end();
      });
      stream.on('end', function() {
        stream.end();
        return console.log('end');
      });
      return stream.on('close', function() {
        console.log('close');
        return stream.close();
      });
    });
  });

  server.listen(8488);

}).call(this);
